services:
  influxdb:
    image: influxdb:2.7.4
    container_name: influxdb
    volumes:
      - influxdb-vol:(...)
    ports:
      - (...):(...)
    restart: (...)
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=(...)
      - DOCKER_INFLUXDB_INIT_ORG=SolarBiz
      - DOCKER_INFLUXDB_INIT_BUCKET=solar_viz_bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=a01396360b78797f0523fde24c86ee31

  grafana:
    image: grafana/grafana:10.2.1
    container_name: grafana
    depends_on:
      - influxdb
      - postgresql
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=(...)
    volumes:
      - grafana-vol:(...)
    ports:
      - (...):(...)
    restart: (...)

  postgresql:
    image: postgres:16.0
    container_name: postgresql_db
    volumes:
      - postgresql-vol:/var/lib/postgresql/data
    ports:
      - (...):(...)
    restart: (...)
    environment:
      - POSTGRES_PASSWORD=(...)
      - POSTGRES_DB=solar_viz_db
      - PGDATA=/var/lib/postgresql/data/pgdata

networks:
  default:
    name: solar_viz_net
    external: true

volumes:
  postgresql-vol:
  influxdb-vol:
  grafana-vol:
